FROM ubuntu:latest
ARG GITLAB_TOKEN
ARG GIT_USER_EMAIL
ARG GIT_USER_NAME
RUN echo "${GITLAB_TOKEN}" > /root/.gitlab_token && \
    echo "GIT_USER_EMAIL=${GIT_USER_EMAIL}" > /root/.gitconfig_info && \
    echo "GIT_USER_NAME=${GIT_USER_NAME}" >> /root/.gitconfig_info
RUN apt-get update && apt-get install -y git
WORKDIR /code/startercode-generator-bs
CMD ["/bin/bash", "/code/startercode-generator-bs/update_renku.sh"]
