---
title: "Open Government Data, provided by {{ PROVIDER }}"
date: "{{ TODAY_DATE }}"
output: html_document
---

## Dataset: {{ DATASET_TITLE }}

{{ DATASHOP_LINK }}

Auto generated R starter code for data set {{ DATASET_IDENTIFIER }}.

## Metadata

{{ DATASET_METADATA }}

# Load packages

```{r}

library(tidyverse)
library(skimr)
library(janitor)
library(VIM)




```

# Load data

The dataset is read into a dataframe

```{r}
get_dataset <- function(url) {
  # Create directory if it does not exist
  data_path <- file.path(getwd(), '..', 'data')
  if (!dir.exists(data_path)) {
    dir.create(data_path, recursive = TRUE)
  }
  # Download the CSV file
  csv_path <- file.path(data_path , '{{ DATASET_IDENTIFIER }}.csv')
  download.file(url, csv_path, mode = "wb")

  # Read the CSV file
  data <- tryCatch(
      read.csv(csv_path, sep = ";", stringsAsFactors = FALSE, encoding = "UTF-8"),
      warning = function(w) NULL,
      error = function(e) NULL
  )
  # if dataframe only has one column or less the data is not ";" separated
  if (is.null(data) || ncol(data) <= 1) {
      stop("The data wasn't imported properly. Very likely the correct separator couldn't be found.\nPlease check the dataset manually and adjust the code.")
  }
  return(data)
}
```

```{r}

{{ LOAD_DATA }}

```

# Analyze data

```{r}

glimpse(df)
str(df)
skim(df)

head(df)
tail(df)

```

# Continue your code here...

```{r}
# Remove columns that have no values with janitor
df <- remove_empty(df, which = "cols", quiet = FALSE)

# Remove rows with missing values (if appropriate)
df <- na.omit(df)

# display a small random sample transposed in order to see all variables
t(sample_n(df, 5))

# the size of the data frame in memory
 size <- object.size(df)
#  the size in bytes
print(size)

# describe numerical features
summary(df[, sapply(df, is.numeric)])

# describe non-numerical features
summary(df[, sapply(df, Negate(is.numeric))])

# check missing values with VIM
aggr(df, numbers = TRUE, prop = FALSE, combined = FALSE, sortVars = TRUE,  plot = TRUE)

# plot a histogram for each numerical feature
df %>%
  select_if(is.numeric) %>%
  gather() %>%
  ggplot( aes(value)) +
  geom_histogram(bins = 10, color = "white", fill = "red") +
    facet_wrap(~key, scales = 'free_x')
```

------------------------------------------------------------------------

# Questions about the data?

{{ CONTACT }}
