# /// script
# requires-python = ">=3.12"
# dependencies = [
#     "marimo",
#     "matplotlib==3.10.6",
#     "missingno==0.5.2",
#     "pandas==2.3.2",
#     "polars==1.32.3",
#     "requests==2.32.5",
#     "tqdm==4.67.1",
#     "ipython==9.17.1",
# ]
# ///

import marimo

__generated_with = "0.15.1"
app = marimo.App(auto_download=["html"])


@app.cell
def _():
    import marimo as mo
    return (mo,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    ## Open Government Data, provided by **{{ PROVIDER }}**
    *Autogenerated Python starter code for dataset with identifier* **{{ DATASET_IDENTIFIER }}**
    """
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    ## Dataset
    # **{{ DATASET_TITLE }}**
    **Description**: {{ DATASET_DESCRIPTION }}

    *You can find the dataset [under this link]({{ DATASHOP_LINK }})*.
    """
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    /// details | Metadata

{{ DATASET_METADATA }}

    ///
    """
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(
        r"""
    /// details | Data dictionary

{{ DATASET_FIELDS }}

    ///
    """
    )
    return


@app.cell
def _():
    import os
    import io
    import pandas as pd
    import requests
    import matplotlib.pyplot as plt
    from tqdm.auto import tqdm
    from IPython.display import display
    return display, io, os, pd, plt, requests, tqdm


@app.cell
def _(plt):
    plt.style.use("ggplot")

    params = {
        "text.color": (0.25, 0.25, 0.25),
        "figure.figsize": [18, 6],
    }

    plt.rcParams.update(params)
    return


@app.cell
def _(io, os, pd, requests, tqdm):
    # helper functions for reading datasets (handles large datasets via chunked/faceted download)
    {{ GET_DATASET_PY_MARIMO }}
    return ensure_data_dir, download_csv_chunk, pick_best_facet, get_dataset


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""## Load data""")
    return


@app.cell
def _(get_dataset):
    # Read the dataset
    df = get_dataset(dataset_id="{{ DATASET_IDENTIFIER }}")
    df
    return (df,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""## Analyze Data""")
    return


@app.cell
def _(df):
    {{ EDA_DROPNA }}
    return


@app.cell
def _(df):
    {{ EDA_SHAPE_DUPLICATES }}
    return


@app.cell
def _(df):
    {{ EDA_INFO }}
    return


@app.cell
def _(df):
    {{ EDA_HEAD }}
    return


@app.cell
def _(df):
    {{ EDA_SAMPLE_TRANSPOSED }}
    return


@app.cell
def _(df, display, pd):
    {{ EDA_DESCRIBE_CATEGORICAL }}
    return


@app.cell
def _(df, display, pd):
    {{ EDA_DESCRIBE_NUMERIC }}
    return


@app.cell
def _(df):
    {{ EDA_MISSINGNO }}
    return


@app.cell
def _(df, pd, plt):
    {{ EDA_HISTOGRAM }}
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""**Questions about the data?** {{ CONTACT }}""")
    return

if __name__ == "__main__":
    app.run()
