name: Update and Push Starter Code

on:
  schedule:
    - cron: '0 8/12 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Create and prepare _work directory
        run: |
          mkdir _work
          cd _work
          git init
          git remote add origin https://github.com/${{ github.repository }}.git
          git fetch origin main
          git checkout -B main origin/main

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.17"

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Install dependencies with uv
        run: uv sync --frozen

      - name: Run updater
        run: uv run updater.py
        working-directory: ./_work

      - name: Commit and push (as github-actions[bot])
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Automated update on $(date -u '+%Y-%m-%d %H:%M:%S UTC')" || echo "Nothing to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
        working-directory: ./_work
