name: Update and Push Starter Code

on:
  schedule:
    - cron: '0 8/12 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Create and prepare _work directory
        run: |
          mkdir _work
          cd _work
          git init
          git remote add origin https://github.com/opendatabs/startercode-opendatabs.git
          git fetch origin main
          git checkout -b main origin/main
          git pull origin main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests tqdm
      
      - name: Run updater
        run: python updater.py

      - name: Commit and push
        run: |
          git add .
          git commit -m "Automated update on $(date -u '+%Y-%m-%d %H:%M:%S UTC')" || echo "Nothing to commit"
          git push origin main
        working-directory: ./_work
        
