name: Update and Push Starter Code

on:
  schedule:
    - cron: '0 8/12 * * *'
  workflow_dispatch:

permissions:
  contents: write

env:
  OUTPUT_DIR: marimo

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Create and prepare _work directory
        run: |
          mkdir _work
          cd _work
          git init
          git remote add origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/opendatabs/startercode-opendatabs.git
          git fetch origin main
          git checkout -b main origin/main
          git pull origin main

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.3"
      
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install dependencies with uv
        run: uv sync --frozen
      
      - name: Run updater
        run: uv run updater.py

      - name: Export marimo apps to HTML (WebAssembly)
        working-directory: ./_work
        run: |
          mkdir -p "${OUTPUT_DIR}"
          # Export each marimo app (*.py in 04_marimo) as run-mode HTML
          for f in 04_marimo/*.py; do
            [ -e "$f" ] || continue
            uvx marimo export html-wasm --mode edit "$f" -o "${OUTPUT_DIR}/$(basename "${f%.py}").html"
          done

          # Ensure Pages doesn’t run Jekyll on this subdir
          touch "${OUTPUT_DIR}/.nojekyll"

      - name: Commit and push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Automated update on $(date -u '+%Y-%m-%d %H:%M:%S UTC')" || echo "Nothing to commit"
          git push origin main
        working-directory: ./_work
        
